const wordData = [
{ word: "春节", pinyin: "chun jie", meaning: "Spring Festival; Lunar New Year" },
{ word: "要求", pinyin: "yao qiu", meaning: "requirement; request; demand" },
{ word: "修改", pinyin: "xiu gai", meaning: "to revise; to correct; to edit" },
{ word: "完成", pinyin: "wan cheng", meaning: "to finish; to complete" },
{ word: "寒假", pinyin: "han jia", meaning: "winter vacation" },
{ word: "过年", pinyin: "guo nian", meaning: "to celebrate the Lunar New Year" },
{ word: "从来", pinyin: "cong lai", meaning: "ever; (often with 不/没) never" },
{ word: "除夕", pinyin: "chu xi", meaning: "Lunar New Year’s Eve" },
{ word: "接着", pinyin: "jie zhe", meaning: "then; next; after that" },
{ word: "爷爷", pinyin: "ye ye", meaning: "grandfather (father’s father)" },
{ word: "奶奶", pinyin: "nai nai", meaning: "grandmother (father’s mother)" },
{ word: "拜拜", pinyin: "bai bai", meaning: "to pray; to worship (at a temple)" },
{ word: "拜", pinyin: "bai", meaning: "to pray; to worship; to pay respects" },
{ word: "祖先", pinyin: "zu xian", meaning: "ancestors" },
{ word: "聚", pinyin: "ju", meaning: "to gather; to get together" },
{ word: "煮", pinyin: "zhu", meaning: "to cook; to boil" },
{ word: "水饺", pinyin: "shui jiao", meaning: "dumplings" },
{ word: "炒", pinyin: "chao", meaning: "to stir-fry" },
{ word: "米粉", pinyin: "mi fen", meaning: "rice noodles; rice vermicelli" },
{ word: "煎", pinyin: "jian", meaning: "to fry; to pan-fry" },
{ word: "萝卜", pinyin: "luo bo", meaning: "radish" },
{ word: "等等", pinyin: "deng deng", meaning: "etc.; and so on" },
{ word: "发财", pinyin: "fa cai", meaning: "to get rich; to make a fortune" },
{ word: "橘子", pinyin: "ju zi", meaning: "orange; tangerine" },
{ word: "更加", pinyin: "geng jia", meaning: "even more" },
{ word: "响", pinyin: "xiang", meaning: "to ring; to sound; to make a noise" },
{ word: "舅舅", pinyin: "jiu jiu", meaning: "mother’s brother; uncle (on maternal side)" },
{ word: "舅妈", pinyin: "jiu ma", meaning: "aunt (wife of mother’s brother)" },
{ word: "亲切", pinyin: "qin qie", meaning: "kind; friendly; warm (in manner)" },
{ word: "相当", pinyin: "xiang dang", meaning: "quite; rather; fairly" },
{ word: "温暖", pinyin: "wen nuan", meaning: "warm; warmth (literal or emotional)" },
{ word: "感谢", pinyin: "gan xie", meaning: "to thank; to be grateful; gratitude" },
{ word: "年夜饭", pinyin: "nian ye fan", meaning: "reunion dinner on Chinese New Year’s Eve" },
{ word: "年糕", pinyin: "nian gao", meaning: "glutinous rice cake; New Year rice cake" },
{ word: "发糕", pinyin: "fa gao", meaning: "prosperity steamed rice cake" },
{ word: "萝卜糕", pinyin: "luo bo gao", meaning: "radish cake; turnip cake" },
{ word: "年年有余", pinyin: "nian nian you yu", meaning: "to have surplus every year (New Year blessing)" },
{ word: "年年高升", pinyin: "nian nian gao sheng", meaning: "to rise higher year after year; to get promoted year by year" },
{ word: "平平安安", pinyin: "ping ping an an", meaning: "safe and sound; peaceful and safe" },
{ word: "大吉大利", pinyin: "da ji da li", meaning: "great luck and great profit; lots of good fortune" }
];
